[theme]
base = "dark"
primaryColor = "#f0a51a"
backgroundColor = "#071018"
secondaryBackgroundColor = "#0b1620"
textColor = "#e8edf2"
font = "sans serif"

[server]
headless = true
address = "0.0.0.0"
port = 7860
runOnSave = false

[browser]
gatherUsageStats = false
